# Generated by Django 3.2.12 on 2022-02-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_user'),
        ('documentos', '0002_documento_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
        ),
    ]
